#--------- This file is automatically generated by LSST's sconsUtils ---------#
__version__ = 'unknown'
__repo_version__ = 'unknown'
__fingerprint__ = '786219475ffd0e022c98234d5b00a5c30ca668c5 *'
__dependency_versions__ = {
}
__all__ = ('__version__', '__repo_version__', '__fingerprint__', '__dependency_versions__')
