#--------- This file is automatically generated by LSST's sconsUtils ---------#
__version__ = '7e0e20a'
__repo_version__ = '7e0e20a'
__repo_version__ = '7e0e20a'
__fingerprint__ = '7e0e20a49629f9b914b5e921879e4db76d400f99 *'
__dependency_versions__ = {
}
__all__ = ('__version__', '__repo_version__', '__repo_version__', '__fingerprint__', '__dependency_versions__')
